inoremap <buffer> <M-a> α
inoremap <buffer> <M-b> β
inoremap <buffer> <M-g> γ
inoremap <buffer> <M-p> π
inoremap <buffer> <M-w> ω
inoremap <buffer> <M-o> ω
inoremap <buffer> <M-f> ϕ
inoremap <buffer> <M-v><M-f> φ
inoremap <buffer> <M-v>f φ
inoremap <buffer> <M-F> Φ
inoremap <buffer> <M-l> λ
inoremap <buffer> <M-L> Λ
inoremap <buffer> <M-e> ϵ
inoremap <buffer> <M-v><M-e> ε
inoremap <buffer> <M-v>e ε
inoremap <buffer> <M-d> δ
inoremap <buffer> <M-D> Δ
